### ISSUE TITLE
Cast & Load M3U

### ISSUE THREAD

**Issue by chienhao10** [sdavides/m3u8-HLS-Homeassistant#1]
Hi Is it possible to cast the video to other entity? I have a list of M3U and full episodes in it. 
ex:
episode 1, xxxx.m3u8
episode 2, xxxx.m3u8
etc...

the webpage can load these episode from user selection and then cast to TV.

**Comment by sdavides** [comment]
no it's not possible

**Comment by sdavides** [comment]
Check back in the next few days, I'm rewriting everything.
I read a list of urls inside the m3u.
I'm working for the cast

**Comment by sdavides** [comment]
see my addon:

https://github.com/sdavides/m3u8-HLS-Homeassistant/tree/main/addon-M3uPlayer
