### ISSUE TITLE
what to insert in URL parameter

### ISSUE THREAD

**Issue by nicolasimeoni** [sdavides/m3u8-HLS-Homeassistant#2]
I don't understand what I have to insert in the URL parameter. Can you give me an example?

**Comment by sdavides** [comment]
url parameter use for download/create file.m3u on /addon_configs/4d8e746b_m3u_player/.
disable = create file.m3u with 1 video
enable = create file.m3u with video list

Update/Apply new config

remember:
Delete "file.m3u"
    ( usually into "/addon_configs/4d8e746b_m3u_player/" )
Update config
Restart

**Comment by sdavides** [comment]
single video: https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.mp4/.m3u8
list video: https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8
